<a href="https://colab.research.google.com/github/Mounika-Bolla/LearnML/blob/main/Numpy_Tutorial_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a Python library. NumPy stands for Numerical Python.


- NumPy is used for working with arrays.


In [ ]:
import numpy as np
#Here numpy is imported under the name of np.

In [ ]:
list = [2, 3, 4, 5]
print(list)

[2, 3, 4, 5]


### **Python List**
- Python List is used to store the one-dimensional array.

### **Advantage of Numpy over Python list**
- NumPy arrays can store Multi-Dimesional arrays.

#**NumPy**

- NumPy strives to deliver an array structure that exhibits a performance improvement of up to 50 times compared to conventional Python lists.
- The array object in NumPy is called ndarray(n dimensional array).

### **Why is NumPy Faster Than Lists?**

- NumPy arrays are stored in a single, continuous memory location, unlike lists. This arrangement allows for efficient access and manipulation by processes, a concept known as "locality of reference" in computer science.

To create a NumPy ndarray object, we can use the `array()` function.

In [ ]:
array = np.array([1,2,3,5,6])
print(array)

print(type(array))
# Here, the type() function gives the type of the object that is passed to it.

[1 2 3 5 6]
<class 'numpy.ndarray'>


To check the Version of the NumPy,

In [ ]:
print(np.__version__)

1.23.5


In [ ]:
# 0-D Array
print("0-D Array")
array0 = np.array(23)
print(array0, "\n")

# 1-D Array
print("1-D Array")
array1 = np.array([1,2,3,4,5])
print(array1,"\n")

# 2-D Array : These are often used to represent Matrices.
print("2-D Array")
array2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(array2, "\n")

# 3-D Array
print("3-D Array")
array3 = np.array([[[1,2,3,4,5],[2,3,4,5,6],[2,4,5,7,9]]])
print(array3)

0-D Array
23 

1-D Array
[1 2 3 4 5] 

2-D Array
[[1 2 3 4 5]
 [6 7 8 9 0]] 

3-D Array
[[[1 2 3 4 5]
  [2 3 4 5 6]
  [2 4 5 7 9]]]


### **Size**

- Gives the number of elements in an array.

In [ ]:

print(array0.size)
print(array1.size)
print(array2.size)
print(array3.size)

1
5
10
15


### **Shape**

- It gives the tuple of number of rows and colums.
- (Rows, Colums)

The shape of an array is the number of elements in each dimension.

In [ ]:
print(array0.shape)
print(array1.shape)
print(array2.shape)
print(array3.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

()
(5,)
(2, 5)
(1, 3, 5)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### **dtype**
- It tells us the type of data present in an array.

In [ ]:
print(array0.dtype)
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

arr = np.array([2,34,6.7,4,5])
print(arr)
print(arr.dtype)

int64
int64
int64
int64
[ 2.  34.   6.7  4.   5. ]
float64


### **Transpose**
- It replaces the rows with columns and columns with rows.

In [ ]:
array3.transpose()

array([[[1],
        [2],
        [2]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [7]],

       [[5],
        [6],
        [9]]])

### **To check Number of Dimensions**
- We use `ndim` to returns an integer that tells us how many dimensions are in the array.

### **Higher Dimensional Arrays**
- When constructing an array, you have the option to specify the number of dimensions through the use of the ndmin parameter.


In [ ]:
print(array0.ndim)
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print('Number of Dimensions :', arr.ndim)

0
1
2
3
[[[[[1 2 3 4 5]]]]]
Number of Dimensions : 5


## **Access Array Elements**
- In arrays, accessing an element is done by using its index number, and in NumPy arrays, indexes begin with 0.

## **Access 2-D Arrays**
- To access elements from 2-D arrays, just use two numbers separated by a comma – the first is the row, and the second is the column, like finding something in a table using rows and columns.

## **Access 3-D Arrays**

- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
sum = 0
arr = np.array([1,2,3,4,5,6])
for i in range(len(arr)):
  sum = sum + arr[i]
print(sum,"\n")

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('4th element on 2nd row: ', arr[1, 3],"\n")

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3-D:",arr1[0,1,1],"\n")

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[0, -1])

21 

4th element on 2nd row:  9 

3-D: 5 

Last element from 2nd dim:  5


# **Array Slicing**

In Python, slicing involves selecting elements from a specified starting index to an ending index. You use square brackets with the format `[start:end]`, and you can also include a step value like `[start:end:step]` for more precise control over the selection.




In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2],"\n")


print("Slicing 2-D Array")
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 4])
print(arr[0:2, 1:4])


[2 3 4 5]
[5 6]
[2 4]
[1 3 5 7] 

Slicing 2-D Array
[7 8 9]
[ 5 10]
[[2 3 4]
 [7 8 9]]


## **Data Types**

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

For i, u, f, S and U we can define size as well.

### **Creating Arrays With a Defined Data Type**

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4') #Create an array with data type 4 bytes integer
print(arr)
print(arr.dtype)

arr = np.array(['a', '2', '3'], dtype='i') # Value Error



[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


ValueError: ignored

## **Converting Data Type on Existing Arrays**

- To change the data type of an array, simply create a copy using the astype() method, specifying the desired type with options like 'f' for float or 'i' for integer.

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

newarr1 = arr.astype(int)
print(newarr1)
print(newarr1.dtype)

arr = np.array([1, 0, 0])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
[1 2 3]
int64
[ True False False]
bool


## **Array Copy Vs View**
- A copy of an array is a completely new array, independent of the original.
- Changes to the copy won't affect the original, and vice versa.
- In contrast, a view is just a perspective on the original array; changes to the view impact the original, and changes to the original affect the view.

### **Check if Array Owns its Data**

- In simpler terms, for NumPy arrays, if the 'base' attribute is None, the array owns the data; otherwise, it refers to the original object, indicating that it's a view and doesn't own the data.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
print(arr)
print(x)
print(y)
print(arr)
print("--------------------------")
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
--------------------------
None
[1 2 3 4 5]


## **Array Reshaping**
- Reshaping an array means altering its form, which is determined by how many elements it has in each dimension. This process allows us to add or remove dimensions and adjust the number of elements in each dimension.

### **Reshape Into any Shape?**

- As long as the elements required for reshaping are equal in both shapes

### **Unknown Dimension**

- You are allowed to have one "unknown" dimension. Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method. Pass -1 as the value, and NumPy will calculate this number for you.

### **Flattening the arrays**
- Flattening array means converting a multidimensional array into a 1D array.
- We can use `reshape(-1)` to do this.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print("-------------------")
newarr = arr.reshape(2, 3, 2)
print(newarr)
print("-------------------")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) #It is a view as it returned original array.
print("-------------------")
newarr = arr.reshape(2, 2, -1)
print(newarr)
print("-------------------")
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

newarr = arr.reshape(3, 3)
print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
-------------------
[1 2 3 4 5 6 7 8]
-------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------
[1 2 3 4 5 6]


ValueError: ignored

## **Array Iterating**

- Iterating involves going through elements one by one. In numpy, when dealing with multi-dimensional arrays, we can achieve this using a basic Python for loop. If we iterate over a 1-D array, it goes through each element individually.

### **Iterating 2-D Arrays**
- It will go through all the rows.

### **Iterating 3-D Arrays**
- It will go through all the 2-D arrays.

### **Iterating Arrays Using nditer()**
- The `nditer()` function is a helpful tool for various levels of iteration, addressing common issues encountered during the process, making it useful for both basic and advanced tasks.

**Iterating on Each Scalar Element**
- Looping through individual elements of a high-dimensional array can be challenging using nested "for" loops in basic programming, requiring multiple iterations.

**Iterating Array With Different Data Types**

- In simple terms, when using the `op_dtypes` argument in NumPy's `nditer()` function to change the data type of elements during iteration, a separate space called a buffer is required for the operation. To enable this, the `flags=['buffered']` parameter is passed. This ensures that the data type change occurs without modifying the original array in place.

**Iterating With Different Step Size**
- We can use filtering and followed by iteration.

Example:

```
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)
```


Output:
```
1
3
5
7
```
**Enumerated Iteration Using ndenumerate()**

Enumeration involves listing items in order, and when we need the position of each element during iteration, we can use the ndenumerate() method for such situations.



In [ ]:
print("1-D Array")
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

print("\n"+"2-D Array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
  for y in x:
    print(y)

print("\n"+"3-D Array")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
  for y in x:
    print(y)
    for z in y:
       print(z)

print("Using nditer() function")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

print("--------Enumerate--------")
arr = np.array([1, 2, 3]) # For 1-D array
for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[1, 2, 3], [2, 3, 4]]) # For 2-D array
for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[[1, 2, 3], [2, 3, 4]]]) # For 3-D array
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1-D Array
1
2
3

2-D Array
[1 2 3]
1
2
3
[4 5 6]
4
5
6

3-D Array
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12
Using nditer() function
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
--------Enumerate--------
(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 2
(1, 1) 3
(1, 2) 4
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 2
(0, 1, 1) 3
(0, 1, 2) 4


# **Array Joining**
- Joining in programming is like combining things. In databases, we join tables using a common link, while in NumPy (a Python library), we join arrays by their arrangement.
- To join arrays in NumPy, we use the `concatenate()` function, specifying the axis along which we want to join them. If the axis is not specified, it's assumed to be 0.

### **Joining Arrays Using Stack Functions**
- Stacking is like combining arrays, but with stacking, it adds a new layer.
- For 1-D arrays, stacking is similar to putting them on top of each other along a new direction.
- You use the `stack()` method and specify the axis, with the default being 0 if not specified.

In [ ]:
# Joining 1-D Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

# Joining 2-D Arrays
arr1 = np.array([[1, 2, 3], [3, 5, 8]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

# Joining 1-D arrays using Stack() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

# Joining 2-D Arrays using stack() function
arr1 = np.array([[1, 2, 3], [3, 5, 8]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)
print("----------")
# "We can use hstack() to stack along rows"
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

arr1 = np.array([[1, 2, 3], [3, 5, 8]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
arr = np.hstack((arr1, arr2))
print(arr)
print("----------")

# "We can use vstack()  to stack along columns"
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
arr1 = np.array([[1, 2, 3], [3, 5, 8]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
arr = np.vstack((arr1, arr2))
print(arr)

print("----------")

# "We can use dstack() to stack along height, which is the same as depth"
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

arr1 = np.array([[1, 2, 3], [3, 5, 8]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]
 [3 5 8 2 2 2]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]
 [3 5 8 2 2 2]]
----------
[1 2 3 4 5 6]
[[1 2 3 4 5 6]
 [3 5 8 2 2 2]]
----------
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [3 5 8]
 [4 5 6]
 [2 2 2]]
----------
[[[1 4]
  [2 5]
  [3 6]]]
[[[1 4]
  [2 5]
  [3 6]]

 [[3 2]
  [5 2]
  [8 2]]]


# **Array Splitting**

- Splitting an array into multiple arrays is the opposite of combining multiple arrays into one. When we want to split an array, we use `array_split()` and provide the array along with the desired number of splits.

**Note:**
- If the array has less elements than required, it will adjust from the end accordingly.
- `Array_split()` adjusts the elements when there are fewer elements in the source array for splitting, unlike `split()` which would fail in such cases.

The `array_split()` method divides an array into multiple parts, and the result is an array containing each split as a separate array. You can then access these individual arrays in the result just like you would with any array element.




In [ ]:
# Splitting 1-D arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 5)
for x in newarr:
 print(x)
print("--------------------------------------")
# Splitting 2-D arrays
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr = np.array_split(arr, 2)
for x in newarr:
  print(x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr = np.array_split(arr, 2, axis = 1)
for x in newarr:
  print(x)

# "We can use hsplit(), vsplit(), and dsplit() opposites of hstack(), vstack() and dstack()""

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr = np.hsplit(arr, 4)
for x in newarr:
  print(x)

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3]
[4]
[5]
[6]
--------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]


# **Array Searching**

- You can find specific values in an array and get their indexes using the `where()` method.

## **Sorted Search**

- The `searchsorted()` method finds where a value would fit in a sorted list and gives the index where it should be inserted.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
y = np.where(arr%2 == 0)
z = np.where(arr%2 != 0)
print(x)
print(y)
print(z)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side = "right")
print(x)

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 6, 6])  #To search for more than one value, use an array with the specified values
print(x) #To maintain the order

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)
1
2
[1 3 3]


# **Arrays Sorting**
- Sorting is the arrangement of elements in a specific order, such as numerical or alphabetical, either from lowest to highest or vice versa. In NumPy, the `sort()` function is used to organize the elements in an array.

In [ ]:
# Sorting 1-D array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array(['Moni', 'Laxmi', 'Niki', 'Kishore'])
print(np.sort(arr))

arr = np.array([True, False, True])
print(np.sort(arr))

#Sorting 2-D Arrays
arr = np.array([[1, 5, 9, 1, 0], [2, 6, 4, 8, 7]])
print(np.sort(arr))

[0 1 2 3]
['Kishore' 'Laxmi' 'Moni' 'Niki']
[False  True  True]
[[0 1 1 5 9]
 [2 4 6 7 8]]


# **Array Filtering**
- Filtering in NumPy involves creating a new array by picking elements from an existing array based on a list of True/False values.
-  If the value is True at a specific index, the element is included in the new array; if it's False, the element is excluded.

**To Create Filtered Array Directly From Array**
- You can replace the iterable variable in the condition with the array directly, and it will function as expected.

In [ ]:
arr = np.array([41, 42, 43, 44])
list = [True, False, True, False]
newarr = arr[list]
print(newarr)

# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])
l = []

for x in arr:
  if x > 42:
    l.append(True)
  else:
    l.append(False)
filtered_array = arr[l]
print(filtered_array)


# Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

l = []

for x in arr:
  if x%2 == 0:
    l.append(True)
  else:
    l.append(False)
filtered_array = arr[l]
print(filtered_array)

# Best Ways to do
arr = np.array([41, 42, 43, 44])
l = arr > 42
filtered_array = arr[l]
print(filtered_array)

arr = np.array([1, 2, 3, 4, 5, 6, 7])
l = arr%2 == 0
filtered_array = arr[l]
print(filtered_array)

[41 43]
[43 44]
[2 4 6]
[43 44]
[2 4 6]
